### ISSUE TITLE
Slugs shouldn't be usable more than once.

### ISSUE THREAD

**Issue by abea** [apostrophecms/apostrophe#1035]
Some confusion/shenanigans happened on Trenton250 when a Page and a Piece show page both had the same slug. The page took precedence and shenanigans ensued. It seems like that shouldn't be possible. Not clear which was created first.

The second that was created should get something like `-0` (or whatever index) appended to differentiate and indicate that something should be fixed.

**Comment by boutell** [comment]
Pages taking precedence is a longstanding policy without which nested blog pages — often used to create a category hierarchy — can't work.

Also in the general case conflicts of this type are hard to prevent. Pieces pages (and other pages) might use [dispatch](http://apostrophecms.org/docs/modules/apostrophe-custom-pages/index.html#dispatch) to map URLs so that they incorporate piece slugs and other components in any number of ways. pieces-pages do it one way by default, blogs and events might remap it to include dates in the URL, etc. 

However we could try doing something like sniffing the URL with an actual http request and flagging if there's something there other than a 404. That would be general enough to detect the problem reliably.

But I could imagine a setup where "dispatch" is accepting anything at all for a path component and not 404'ing even if doesn't find something, and so it would never 404. Maybe it even creates a piece in that situation, wiki-style. Rare but possible.

So I think this would have to be an advisory, not a forced change to "-0". The policy of a page taking precedence over an inexact match of a parent page that runs through "dispatch" has been with us for a long time and changing it would be a bc break, but giving advice would not be.

**Comment by boutell** [comment]
The workaround I suggested was too likely to generate false positives and this hasn't motivated action in two years, so closing.
