### ISSUE TITLE
Apostrophe should have minimum requirements for passwords

### ISSUE THREAD

**Issue by abea** [apostrophecms/apostrophe#1056]
We should check for password strength and have a minimum standard for password creation. Looks like there are [several options in NPM](https://www.npmjs.com/search?q=password+strength) that we could investigate.

**Comment by boutell** [comment]
Please not the "one capitalized, one number, one punctuation" rule. It is worse than useless and its progenitor has disowned it. A minimum length and a check that it's not a dictionary word plus a number, maybe.

owasp-password-strength-test looks promising.

This should probably be a warning rather than a hard and fast policy if you're an admin / at the command line.

**Comment by abea** [comment]
I wouldn't object to closing this if we decide it's not the right move. This was born of seeing many truly terrible client passwords. Using it as a warning system might be fine as an educational tool.

**Comment by boutell** [comment]
I'm not saying it's the wrong move. There are some classes of truly terrible passwords, and that owasp module appears to recognize that passphrases (which usually flunk bad standards) are actually much more secure than short passwords.

**Comment by boutell** [comment]
This has been hit, we now have options to improve password security, see the apostrophe-login and apostrophe-users module documentation.
