### ISSUE TITLE
apos.prefix is doubled on req.redirect = page._url 

### ISSUE THREAD

**Issue by kolbma** [apostrophecms/apostrophe#1168]
If I do a req.redirect = page._url the path in the Location-header gets two times the apos.prefix.

page._url = /prefix/path

Location: /prefix/prefix/path

**Comment by boutell** [comment]
That's true. It's because the `res.redirect` method is overridden so that all the redirects in ordinary everyday Apostrophe code don't break in the presence of a prefix, and we don't have to specify the prefix absolutely everyplace. But, it's inconvenient if you already have the prefix, as with `._url`.

However, it doesn't happen if the URL is absolute. So you can fix this by setting the top level `baseUrl` option, which gets baked into `_url`. In dev, set it to `http://localhost:3000`; in production, set it to the actual base URL for your domain. You want to do this anyway so that you can use `._url` in Facebook og:meta tags and other situations that require an absolute URL.

Note that `baseUrl` *does not* include the prefix, that's already a separate option.

Currently that's the answer to your question (just set `baseUrl`). I suppose we could further override res.redirect so that you can optionall just pass a page object to it, and expect it to look for `_url` and not prefix it since `_url` is already prefixed.
