### ISSUE TITLE
Joins filtering by field value

### ISSUE THREAD

**Issue by arti5m** [apostrophecms/apostrophe#1246]
This is a feature request.

**Scenario:**
I have a `posts` piece that has a select field `postType` with 'news' or 'event' as options. 'News' and 'Event' pieces display differently but are listed and filterable on the same index page. I'm trying to create a Featured event widget that limits the editor to choosing only `posts` with an 'event' `postType`.

**Comment by boutell** [comment]
Mixing posts and events as a single type usually turns out badly because events naturally display as starting with the first one that hasn't already ended, display in ascending order of start date." While posts appear as "starting with the newest one whose publication date is not in the future, display in descending order of publication date."

Think carefully before entering here. We wind up undoing this a lot after sites launch and that is expensive.

That being said: since a cursor filter method is added automatically for all fields of type `select`, you can do...

```
name: '_post',
type: 'joinByOne',
filters: {
  postType: 'event'
}
```

**Comment by stuartromanek** [comment]
🚨 whaaaat 🚨

**Comment by arti5m** [comment]
:upvote:
