### ISSUE TITLE
Proposal: in-place editing in separate modal

### ISSUE THREAD

**Issue by lappalj4** [apostrophecms/apostrophe#1373]
Styling of (in-place) editable components is quite a big pain at the moment, due to the nesting of the actual content rather deep inside various editor-related divs (#1326). Take for example this situation, where I want to provide an in-place editable rich text field, but don't want to give the user any control over the style or alignment of the text:

![image](https://user-images.githubusercontent.com/11797156/40047452-3259b382-5838-11e8-99f8-07ccaf5c786e.png)

```
<div class="widget__image-section">
    <div class="content">
        <div class="text-left">
            {{ apos.singleton(data.widget, 'contentLeft', 'apostrophe-rich-text') }}
        </div>
        <div class="text-right">
            {{ apos.singleton(data.widget, 'contentRight', 'apostrophe-rich-text') }}
        </div>
    </div>
    <img class="background-image" src="{{apos.attachments.url(data.widget.backgroundImage)}}"/>
</div>
```

...there are maybe around 10 "extra" divs between my `text-left` and `text-right` wrapper divs and the actual text field, when all I really want is to have the text be the immediate child of my wrapper divs.

# Proposal

Could we have an option to have the editor be in a separate popup modal, instead of in the textfield itself? In essence: 

* Hovering over the element would show the toolbar, like it does now, with an additional `edit` button
![image](https://user-images.githubusercontent.com/11797156/40048162-30863790-583a-11e8-90ad-a0cae50005f9.png)

* Clicking `edit` would open a modal next to the element containing the same kind of unstyled edit field as would appear in the admin ui, and any changes would be synced with the actual element, so you could see how the result looks

This would get rid of any extra markup in my component, and would still retain the feel of in-place editing, only difference being that the editing does not happen in the textfield itself.

**Comment by stuartromanek** [comment]
Hi @lappalj4, you can accomplish this a few ways.

If you want the user to enter **only** text you might sub in a string field and then output the contents directly into your template like 

```
  <div class="the-string">
    {{ data.widget.theString }}
  </div>
```

If you wanted the user to have some (even very limited) control of text the way a rich-text-widget would provide, you can provide that rich text widget as a field in your widget configuration and then output only its rich text content directly into your template:

```
  <div class="the-rich-text">
    {{ apos.areas.richText(data.widget.theRichText) }}
  </div>
```

This would make for a tidier output
![image](https://user-images.githubusercontent.com/1889830/40053291-b05628f8-580e-11e8-8189-aef7f4ec2b28.png)

Because neither of these are using a contextual view for editing, they now have to be edited in original Edit Widget modal window.
