### ISSUE TITLE
Should/Could we minify HTML?

### ISSUE THREAD

**Issue by abea** [apostrophecms/apostrophe#1499]
An SEO consultant dinged an Apostrophe site we built for not minifying the HTML files. It was among some other very nit-picky things, but it got me wondering. Would this be an easy enough thing to make happen?

**Comment by boutell** [comment]
We're using gzip transfer encoding, so that seems like an odd expectation. The difference in bytes transferred should be trivial with gzip encoding in play. I would point that out to the consultant, perhaps after trying an HTML minifier on the page and comparing what file size you get for each with gzip.

**Comment by houmark** [comment]
Agreed, the difference is very minimal, but it could be a configurable option.

It's important to remember that minifying can take milliseconds also, so what may be saved on bytes transferred is lost minifying the HTML.

SEO people have to find something, and you can always find something, no site is 100% perfect imho. For example, in a perfect world all assets should always live on a cookie free subdomain to prevent sending cookies with asset requests, but those types of configurations we normally do for really large and traffic intense sites.

**Comment by nofwayy** [comment]
You can always configure your Apache/nginx/HA to do the gzip for you anyway. Don’t think this is relevant to do at application level
