### ISSUE TITLE
Evaluate what ES6 features we're using and what the coding standards are (write ES Lint)

### ISSUE THREAD

**Issue by stuartromanek** [apostrophecms/apostrophe#1583]

**Comment by boutell** [comment]
Logged out requirements should be extremely lean because it's basically none of our business what devs choose to support there, so it looks like we'll just merge in apostrophe-lean-frontend, which is fine back to IE8. Logged in... do we support IE11? That would require us to use the compatibility build of Vue 3, but IE11 support isn't going away as an issue any time soon (October 2025!).

**Comment by boutell** [comment]
There is also the issue of devs wanting to use the logged-in capabilities of Apostrophe for public experiences ("sign up for an account").

We can use babel builds that push polyfills only to browsers that need them. It makes sense to pay that freight only where it's required.
