### ISSUE TITLE
How can users change their password?

### ISSUE THREAD

**Issue by shauravg** [apostrophecms/apostrophe#1609]
Is there a way besides password reset where users can change their own password? It seems like currently, once the admin creates the user with a specific password, that user is stuck with that password.

**Comment by boutell** [comment]
They are not stuck, you can enable the password reset feature that you mentioned, this requires the user receive an email which is intentional as a guard against hijacking of accounts.

HOWTO for activating this feature:

https://apostrophecms.org/docs/tutorials/howtos/password-reset.html

Users can then access it right from the login page.
