### ISSUE TITLE
Switch of "a" to "button" broke drag and drop of widgets

### ISSUE THREAD

**Issue by boutell** [apostrophecms/apostrophe#1680]

**Comment by abea** [comment]
It looks like this might be due to the default behavior of the button. [Suggestion here to use preventDefault to allow for dragging](https://stackoverflow.com/a/6875184/888550).

I'm also seeing suggestions of using `.draggable({cancel:false});` in that SO and [the jquery UI forum](https://forum.jquery.com/topic/draggable-button).

Also, an interesting demo for accessible drag-drop linked from the w3c: https://dev.opera.com/articles/accessible-drag-and-drop/example.html, maybe more for 3.x, phase 2.
