### ISSUE TITLE
Lots of user / logged-in / jquery-ui CSS pushed to anon scene

### ISSUE THREAD

**Issue by stuartromanek** [apostrophecms/apostrophe#1698]
Noticed this when looking through CSSStats for new demo. Why is this the default case @boutell ?

https://cssstats.com/stats?url=http%3A%2F%2Fopenmuseum.punkave.net&ua=Browser%20Default

**Comment by boutell** [comment]
Because we made some sloppy choices, but we should use
apostrophe-lean-frontend anyway to put our best foot forward, yeah?

**Comment by boutell** [comment]
This issue is resolved by `apostrophe-lean-frontend` for 2.x and 100% of the time for 3.x. Making backwards incompatible reductions in what is pushed to 2.x is not a good option. We could come up with some kind of middle ground, but I think porting projects where this is an issue to lean-frontend - including our demo - would make more sense. Even though it means porting our ajax stuff to work with lean-frontend.

**Comment by boutell** [comment]
(We will want that for 3.x anyway.)

**Comment by boutell** [comment]
It can be an optional inclusion in lean-frontend, just like the video widget js.
