### ISSUE TITLE
Batch performance with big data?

### ISSUE THREAD

**Issue by giorgio79** [apostrophecms/apostrophe#1800]
Wonder if any tests were performed batching thousands of records?

**Comment by boutell** [comment]
I did it just the other day. It works fine, because it's designed to run a self-contained method to process each item independently, so there's little temptation to "try to do the whole job in RAM," etc.

It's not especially fast because the operations are currently one at a time. We could probably switch this to use `eachLimit` with a reasonable limit, like 5, with no ill effects but we started out with a conservative implementation to err on the side of reliability. In theory there could be a batch operation that can't be run with concurrency but I can't think what that operation could reasonably be, given that ordinary manual operations on single documents could trigger that situation too anyway if they happen to be simultaneous.

Going to close because the question is answered, but a PR to switch it up to run more than one at a time subject to a limit would certainly be considered.
