### ISSUE TITLE
Route overwrite fails

### ISSUE THREAD

**Issue by Jose96GIT** [apostrophecms/apostrophe#1805]
I'm overwriting some methods and routes from apostrophe-signup, so I put my own routes and methods in  /**_lib/apostrophe-signup/_** 

The methods I overwrite are correct, but when I overwrite the route and I call to my route, it calls the route that it's defined in /**_node_modules/apostrophe-signup/_** 

How can I overwrite I route having the same name that the original route definition?

**Comment by stuartromanek** [comment]
Can you provide the code for your overwrite?

Also, this sort of How To question is probably more valuable on Stack Overflow https://stackoverflow.com/questions/tagged/apostrophe-cms

**Comment by Jose96GIT** [comment]
This is the code I was talking about, as I said before it is located in /**_lib/modules/apostrophe-signup/_**

I only have problems with the GET route.

[overwrite.zip](https://github.com/apostrophecms/apostrophe/files/2899529/overwrite.zip)

**Comment by stuartromanek** [comment]
The way that `apostrophe-signup` was written, the routes are being applied from apostrophe directly to express. This doesn't allow for an override of the route itself.

A PR we'd take that _would_ allow this would add a method to `apostrophe-signup` that applies the routes and calling it from `afterConstruct`. This way the method itself could be overridden, letting you redefine the route logic.

In your code you're going to a lot of trouble to define schemas in your signup override code instead of supplying the module with the fields you want the user to fill out (see example configuration in README, `fields` https://github.com/apostrophecms/apostrophe-signup#apostrophe-signup). 

Can you explain what are you trying to do? There might be another way to handle this.

**Comment by Jose96GIT** [comment]
What a was trying to do is that in the signup of the user, the fields "firstName", "lastName", "email" and "password" must be fill by the user, and the "username" is an union of the firstName and the lastName, so to change the required fields, I refined the default user schema.

In reference to the PR, I'd be pleasure if you can evaluate its difficulty because I'd be interested in resolving it.

**Comment by stuartromanek** [comment]
You can customize the username generation by hooking into the `beforeInsert` method, which is run before inserting the new record into the db and provides you with the initial user data that the new signup has supplied.

in your project level `/lib/modules/apostrophe-signup/index.js`
```
module.exports = {
  construct: function(self, options) {
    self.beforeInsert = function (req, user, callback) {
      user.username = user.firstName + '-CUSTOM-FORMATTING-HERE';
      return callback(null)
    }
  }
};
```

**Comment by stuartromanek** [comment]
An example of where Apostrophe add routes from a method in `afterConstruct` you can look over the `apostrophe-login` module.

https://github.com/apostrophecms/apostrophe/blob/master/lib/modules/apostrophe-login/index.js#L56

**Comment by boutell** [comment]
I'm going to close this issue because it's not a bug, but feel free to pursue the PR Stuart suggests.
