### ISSUE TITLE
Modal delay when a piece has a significant amount of rich text widgets.

### ISSUE THREAD

**Issue by ghost** [apostrophecms/apostrophe#1808]
Good morning,

We noted a significant delay when opening a piece modal or creating a new one. This piece has 16 rich text widgets (singleton) and 8 joins (projections are in their place). It was not an issue while working in local but it became one the moment we deployed it in a server. 

We used apostrophe-profiler and examined it with chrome dev tools and noticed that it uses ajax every time a widget needs to be loaded. 

Is there a way to improve this performance, lazy loading maybe.

We are attaching a small project with a piece with the same structure as the one we are having problems with. 

Thanks

[delay-project.zip](https://github.com/apostrophecms/apostrophe/files/2904933/delay-project.zip)

**Comment by boutell** [comment]
I think your diagnosis is correct, yes. This could be an area for a community contribution, or for enterprise support if you'd like to pursue that option. It probably will be a while before we otherwise have time to address it, but possibly in 3.x.

**Comment by Jose96GIT** [comment]
I'm trying to reduce the delay time of the piece modal when you want to create a or edit a piece and I've notice that editing a piece does the double of the requests than creating a new one. Is there any reason for this?

I also be pleasure if you could tell me how to improve it. I'll be ready for trying to do a PR.

**Comment by boutell** [comment]
This is the edit-virtual-area route. The simplest fix might be to delay
these requests a tenth of a second and batch them up, sending them as an
array in a single request.

**Comment by Jose96GIT** [comment]
I'm trying to resolve this PR, but I have some doubts due to my lack of knowledge of how the Apostrophe-core really works. 

Passing an array and overriding all the methods involved, I found a problem in the apostrophe-templates renderBody method, in this part of the method.

```
if (type === 'file') {
   var finalName = s;
   if (!finalName.match(/\.\w+$/)) {
     finalName += '.html';
   }
  result = (env.getTemplate(finalName).render(args));
}
```
I tried two different changes:

1. Join all the rich-text results in an only result, having a string. The problem with this, is that at the end, in the callback of the edit-virtual-area I have to split it to show into the modal, and also that my rich-text widget is a singleton, but when I show it, it's like an area, I don't know why is this happening because I don't understand the whole behaviour of the chain methods that are called during the POST method.

2. Create a result array, with a indepedent rich-text widget in each position, but the problem with this is that in the callback in the **apostrophe-schemas->user.js** file I can't show properly in the modal. Also I noticed that the code that returns to show each rich-text changes, as well as it's coverted to a string before arrive to this part of the code, and I don't know where.

Please, can you guide me to continue with this PR?

Thanks in advance!

**Comment by boutell** [comment]
My thought here is:

* edit-virtual-area invocations get intercepted on the browser side and put on a queue instead, debounced by about a quarter second.
* When that times out without another invocation, a single request to the API is made, with an array of content rather than an object.
* The route on the server side uses the same logic it has now, except that it groups together all the requests that would modify the same doc id so it only has to lock/fetch/save/unlock once.

**Comment by Jose96GIT** [comment]
Hi Tom. I've returned to try to resolve this issue and I've found a problem with the returning data. 

I'm passing an array with all the rich text, and applying the same procedure to all the array elements, but I'm having problems with `renderArea` helper method.

As I don't want to modify this method, because it would affect to many other places. So I don't know how to solve it, without affecting other functionalities.

Thanks in advance!
