### ISSUE TITLE
Developers should be able to deploy effectively to Heroku without building assets in dev

### ISSUE THREAD

**Issue by punkhub** [apostrophecms/apostrophe#1866]
Update the `apostrophe:generation` task so that if `--create-bundle=db` (rather than an old fashioned bundle name that would live in the repo), it builds the asset bundle and then stores the latest asset bundle version number *in the database*. Then copies the entire bundle to uploadfs *as a zipfile with the version number in the filename*.
• Update apostrophe startup so that if APOS_BUNDLE=db (rather than an old fashioned bundle name to be found in the repo), it looks at the asset bundle version number *in the database* and downloads the appropriate zipfile from uploadfs. Then extracts the bundle as it would now.

This way, the `apostrophe:generation` task can be moved to the Heroku release phase, without running into the problem that files are not persistent in Heroku.

… And that means pushing to `production` or clicking build in Heroku is sufficient to do a complete and performant Apostrophe deployment to Heroku.

**Comment by boutell** [comment]
I think this should be `--create-bundle` with no argument, and `APOS_BUNDLE=1`, to emphasize that it's the preferred way to go. But we do need to maintain the support for the bundle arriving via git/the filesystem because an enterprise client prefers not to have any production database access in the asset build process.

**Comment by boutell** [comment]
There is a PoC implementation here: https://github.com/apostrophecms/apostrophe/compare/1866-simple-bundles?expand=1

Next step is to actually test this in Heroku rather than with the uploadfs local backend, although it shouldn't matter we need to feel it out in practice.

Then test a bunch of boring legacy scenarios to make sure we don't break them!

After this, `--create-bundle` with no name and `APOS_BUNDLE=1` will be the strongly recommended way to fly.

**Comment by boutell** [comment]
Aaaand the simplification of "developer UX" around this feature continues in the latest commit!

```
# In Heroku prelaunch script - runs in a worker dyno, can see production db
APOS_BUNDLE=1 node app apostrophe:generation
# To launch site in production
APOS_BUNDLE=1 node app
```

That's it, that's all! So only one thing to remember to do:

```
heroku config set APOS_BUNDLE=1
```

And then you do the intuitive thing in Heroku: you run `apostrophe:generation` with no arguments at all in the prerelaunch script, and you run Apostrophe with no special arguments (plain npm start). Victory. I hope. Must test.
