### ISSUE TITLE
Root/Home page content is not copied anymore

### ISSUE THREAD

**Issue by sambadevi** [apostrophecms/apostrophe#1877]
**To Reproduce**
1. `apos create-project <project-name>`
2. `cd <project-name>`
3. Change apostrophe version in package.json to 2.87
4. `npm i`
5. Create admin user for apostrophe with `node app apostrophe-users:add admin admin`
6. Start with `node app.js`
7. Add some editable content to your page ( see https://docs.apostrophecms.org/apostrophe/tutorials/getting-started/adding-editable-content-to-pages )
8. Page-Menu -> Copy Page, give it some name and slug
9. The result will be an empty page and the slug will lead to `/none`

**Expected behavior**
A copied version of root as child element to the root page with the same content as on the root page

**Describe the bug**
After #1176 got resolved, apostrophe allows the root page to be copied now, it was working for some time and everything went fine, however no content is taken over to the child page anymore.

**Version of Node.js**
`node -v` shows 11.14.0

**Server Operating System**
Dev Environment running Linux

**Comment by stuartromanek** [comment]
I've started a branch looking into this, it seems like a two part'er

https://github.com/apostrophecms/apostrophe/tree/copying-home-bugs

The first was that in figuring out we are copying the homepage we leave that page object behind and clone properties from the empty `sibling` variable, which is used in cases where we're NOT copying the homepage. This is fixed.

What I can't get is that the slug (which starts propped up as `/new-page`) get garbled during `schemas.convert` and comes out at `/none[andmaybesomenumbers]`. It looks like this is failing the slug test and getting assigned some fallback.

The other thing is that the front-end JS that keeps the title and slug in sync during page creation does not fire up in the Copy modal *when the copied page is /*. This handler does fire up in children pages during copy.

**Comment by sambadevi** [comment]
@stuartromanek any idea if this will be fixed/merged before 3.0 ?

**Comment by stuartromanek** [comment]
Hi @sambadevi , I've dug back into this. I want to get @boutell's thoughts on a fix

*What is happening*
- Site comes with home page at root level. 
- Page Settings modal wants to keep the page title and slug in sync /unless/ it detects you’ve changed the slug independently of title (it is implied you’ve done this on purpose)
- Root level page is exempt from the keep-title-in-sync dance because the slug has to remain `/`
- When *copying* the home page, you are copying a page where the title and slug have already been divorced, so the slug field doesn’t get auto populated. Leaving the slug blank conflicts with real homepage at `/` and you get these gross corrected slugs `/none389`

*Proposed Solution*
- When copying a page we should force that reunion between page title and slug to happen

**Comment by boutell** [comment]
Makes sense to me.

**Comment by stuartromanek** [comment]
PR out in #1924

**Comment by stuartromanek** [comment]
Hey @sambadevi this fix has been merged and will be part of our next release, which will probably be around the end of this week. Thanks for the issue!
