### ISSUE TITLE
truncate rich text

### ISSUE THREAD

**Issue by alialroomi** [apostrophecms/apostrophe#1979]
dears,

i need help in truncate a text from rich text  as below please i tried many but useless 

   {% for piece in data.pieces %}
                       
                            <div class="col-md-4 col-sm-6">
                                <div class="single-product mb-55 animated fadeInUp" data-animate="fadeInUp" data-delay=".1" style="animation-duration: 0.6s; animation-delay: 0.1s;">
                                    <span class="tip">{{ piece.title }}</span>
                                    <img src="img/products/product1@2x.jpg" data-rjs="2" alt="" data-rjs-processed="true" width="237" height="193">
                              
                                    <h3 class="h5">
                                       {{ apos.area(piece, 'body') }}
                                    </h3>
                                  
                                </div>
                            </div>
                          
                            
                        {% endfor %}

i need to truncate this part i don't know if there is other way to display the description 

{{ apos.area(piece, 'body') }}

thanks in advance

**Comment by boutell** [comment]
You can obtain the rich text markup only, discarding all other widget content etc., with `{{ apos.areas.richText(piece.body) }}`. However this does not give you a means of truncation that respects tag boundaries and tag closure. Most websites, including YouTube, solve that problem using CSS (fixed height, overflow hidden, and a CSS gradient) rather than truncation based on word or character count.

However, if you are OK with plaintext only, you can use:

`{{ apos.areas.plaintext(piece.body, { limit: 300 }) }}`

To limit to 300 characters. Plaintext only means you will not get any rich markup.

Closing as I believe these techniques most likely cover your use cases.
