### ISSUE TITLE
Question: How to generate secret? And how "secret" does it need to be?

### ISSUE THREAD

**Issue by TheBabu** [apostrophecms/apostrophe#2212]
In `lib/modules/apostrophe-express` it tells that there must be a secret in the session:
```
module.exports = {
  session: {
    // If this still says `undefined`, set a real secret!
    secret: 'XXXXXXXX'
  }
};
```
How would you go about generating a secret, in my case I am importing my project from github so the secret from my local project will already be there.

And more generally, what does this secret do? How unsecure will my project be if this secret was leaked?  And how much of a secret does this need to be, *I'm guessing a bit*.

**Comment by boutell** [comment]
There's a good discussion here:

https://martinfowler.com/articles/session-secret.html

If you know the secret and the session IDs can be guessed at, then there's a risk of hijacking another user's session, i.e. gaining admin access. A highly random string, i.e. a secure password, is a good choice of secret because it ensures this isn't possible.
