### ISSUE TITLE
3.x: page modules and the `name` option

### ISSUE THREAD

**Issue by abea** [apostrophecms/apostrophe#2780]
Thread pulling time. The facts (that you can correct me on):

- As an inherited pattern, in A3 all page types can be referenced as `@apostrophecms/page`. This is because all pages are a single doc type, even if they're different page types.
- In 2.x, this same convenience was `apostrophe-page`.
- In 3.x, there is a module already named `@apostrophecms/page`, but in 2.x there is _not_ a module called `apostrophe-page` (it's `apostrophe-pages`).
- In 3.x, this pattern is implemented in the doc type module, `@apostrophe/any-page-type` (in 2.x it was `apostrophe-custom-pages`)
- To get this all working, `any-page-type` gets the option, `name: '@apostrophecms/page'`. Things are already getting confusing...

**The problem is appearing as we're going to remove the `name` option from doc type modules.** It's rarely used and we can be simpler and more consistent if we use the meta name that most use anyway (`self.__meta.name`). But because of the convenience covered above, our relationship fields have been using `@apostrophecms/page` to reference any page. This is complicating removing that option and causing errors.

- Option 1: We use `@apostrophecms/any-page-type` to reference all pages instead. The most significant context would probably be in relationship fields. It's new and thus scary, but is it bad?
- Option 2: We use another name altogether. I don't know what.
- Option 3: We continue to use `@apostrophecms/page` and figure out how to rig up `any-page-type` to work without the `name` option. The biggest argument in favor of this is that all the REST API routes use this "name" as well, so all page _stuff_ uses the same term. It does seem... weird... and maybe bad that we're using the name of a related-but-different module as the "name" of another module.

**Comment by agilbert** [comment]
Can you include a full example of how this issue manifests in the module configuration?

**Comment by boutell** [comment]
Thanks for writing this up Bea.

To summarize the summary of the summary, in A3 every module's module name is its *only* name. We don't have to worry about any distinction between the `type` property that will be in the database, the name you use when you create a relationship to it, and the name of the module. That's all gone. One thing. Yay!

Except for this one place: a relationship with "any page type." As is commonly used to create navigation:

```javascript
_footerLinks: {
  type: 'relationship',
  with: '@apostrophecms/page'
}
```

This is powered, under the hood, by a module called `@apostrophecms/any-page-type` but in the relationship we write `@apostrophecms/page` because back in 2.x, where the `name` (the type in the database) never matched the module name (unless you were ahead of your time and I wasn't looking), I thought it was cute to write `apostrophe-page` here.

So as the guy who originally made this mess, on both counts, here's my take:

It is not worth perpetuating the distinction between `name` and the name of the module just for this one case, and if I were not an experienced A2 programmer, I would not find "just write `with: @apostrophecms/any-page-type` when you want to join with **any type of page**" to be unreasonable. I'd find it explicit and memorable. And I also wouldn't pick up a seed of unhealthy curiosity about whether `@apostrophecms/page`, the module, is a doc type (it ain't).

**Comment by abea** [comment]
> if I were not an experienced A2 programmer (and thus had no pre-existing expectations), I would not find "just write with: @apostrophecms/any-page-type when you want to join with any type of page" to be unreasonable.

I agree with this and am struggling to put myself in this mindset. The thing I'm not sure if I appreciate yet is whether someone would see "join to _any page type_" and think, "okay, then can I join to one specific page type?", which you cannot.

**Comment by boutell** [comment]
Joining with one specific page type ought to be fine, actually. I think it works in 2.x? It should work. I'd like it to work. LOL.

**Comment by boutell** [comment]
I guess the problem there would be the lack of a manager experience for picking those pages of a single type. Not that hard to get the pieces manager to function in that role with all editing capabilities disabled. You could do something zanier like editing the page tree with selection of other types disabled, but other types visible in the tree where they create necessary structure. I don't know man.

**Comment by abea** [comment]
Correct. Probably go with the piece manager option since in that context you don't really care (?) about the page tree. But that's a problem for another day. The answer for now might be that "any-page-type" is okay since One Day we'll be able to join to specific page types selectively.

**Comment by stuartromanek** [comment]
Sure, it's sort of a strange meta name but not unreasonable or bad, and not seemingly _wrong_ when encountered first in documentation, I'd think

**Comment by abea** [comment]
`@apostrophecms/any-page-type` is the way. https://v3.docs.apostrophecms.org/guide/relationships.html
