### ISSUE TITLE
3.x: Removing `options` argument from module config sections

### ISSUE THREAD

**Issue by abea** [apostrophecms/apostrophe#2785]
## The problem to solve

Right now in A3, similar to A2, module configuration function sections (including the `methods`, `fields`, `helpers`, and `apiRoutes`) get two arguments: `self` and `options`. `self` is a reference to the module and `options` is the actual options object section defined on the module.

The "problem" appears when we or Apos developers use that very useful variable name, "options," within those function sections. In some cases a module method may take its own set of options. Either the dev needs to use another argument name (e.g., `opts`) or potentially create confusing code where other devs might not understand which `options` argument is being used in a context.

To be transparent, this has actually resulted in A3 core bugs where module methods originally had their own `options` arguments, but then those were removed. But because that argument name was used in the parent context, it took a while to realize that we missed some code cleanup.

It's also redundant. In these `(self, options)` function arguments, `options` is the same thing as `self.options`. More on that next.

## Proposed solution

We deprecate and remove the `options` argument in module section functions. Instead of `methods(self, options)`, devs will write it as `methods(self)`. The downside of that is that you need to write `self.options` to get that options object instead of `options`. Five additional characters.

The benefit of this is additional clarity and that it's harder to make mistakes when using an options object. Once this change is made, if `options` is used in a module you can know it's some variable unique to a specific context. If `self.options` is used, you can know that it's referring to the module's options.

If you ever set `const options = self.options;` you're taking that risk on yourself and may God have mercy on your soul.

## Alternatives

We do nothing? Other than document that you should name your own options as `opts`, maybe.

## Additional context

This is another thing to update in migrations from 2.x, but compared to all the rest you'll need to do in migrating module configs, it's relatively minor in my opinion. An automated module migrator might struggle to parse the options, however any automated tool should get a second review by a developer anyway.

**Comment by abea** [comment]
There's a secondary question of whether it should be removed from core function usage and discouraged or actually removed as an option altogether. The former would be less of a change for experienced Apos devs, but less of a win. An A2 dev could mindlessly add it back in and miss out on the intended benefits.

**Comment by jogarijo** [comment]
I agree with the proposed solution.

I've been working with A2 for about 3 years now, and I'm quite used to seeing/using `options`. I honestly think I would probably miss it at first (because as you said `self.options` is indeed more cumbersome to write than just `options`), but that would be for the best in my opinion.

In fact, I often had to explain to confused newcomers that `self.options` and `options` are actually the same thing. I was myself confused the first few times I saw `self.options` and `options` being used a couple lines apart.

Moreover, as `self` already embeds, well, everything (thanks to `self.apos`), not having an extra parameter would advertise it more efficiently, too.

**Comment by abea** [comment]
Right. Thanks for your thoughts there, @jogarijo. I don't want to suggest that the `options` argument has no value. It's biggest value might be in that it makes it more obvious that these options are available in those contexts for devs to use.

Hopefully we can make that clear in documentation so we don't need that extra sign post.

**Comment by ecb34** [comment]
I agree with the solution, it's unnecesary to have options when you have it on self.options

**Comment by myovchev** [comment]
This one is very painful but indeed required change. I'm all for it. From my perspective, it's exactly the case you describe - in the years my coding habits led me to implement a coding style disallowing (eslint) using root scope variables in child scopes. And while on first glance it is OK as JS scopes them as expected (things get very messy if you are still using `var`), it hurts readability and increases the (scientific) chance of producing a bug. 

I'll be happy to get rid of all those `opts`, `_options`, unused `options` arguments in my code no matter the effort. In fact the refactoring is not that painful 
```js
// before
fn(self, options) {
  // ...
}
// after
fn(self) {
  const { options } = self;
  // ...
}
```
It could be even be automated with a script to some extent.

+100 on this.

**Comment by myovchev** [comment]
One more thing - now that module `options` live in their own key of the module export, it's very intuitive to reference them with `self.options` even if you don't use the documentation.

**Comment by boutell** [comment]
I'm all for it. `options` is so often the last argument to a method that it feels like asking for trouble to have it also exist in the outer scope, and it also makes the one in the outer scope useless anyway in that situation.

The only counterargument I can come up with is that it might not come up if a method's optional arguments are written in destructuring style:

```javascript
methods(self, options) {
  async insert(req, doc, { permissions = true }) {
    // There is only one "options" visible here because "permissions" was destructured
  }
}
```

However this is not as great as it sounds because many methods need to pass on all or most of their options to another method or to a base class, and it creates bc breaks if we demand that their authors know about it every time a new option is added to the other method:


```javascript
methods(self, options) {
  async insert(_super, req, doc, { permissions = true, otherThing: false, thirdThing: 'cool' }) {
    // Will fail as soon as "fourthThing" is introduced as an option of doc.insert
    apos.doc.insert(req, doc, { permissions, otherThing, thirdThing });    
  }
}
```

So even in this case there are times when an "options" parameter to the method is preferred, and getting rid of "options" in the outer scope is a solid win.

**Comment by myovchev** [comment]
Well spotted, I don't have the habit of destructing arguments since my first steps in Typescript (the auto complete of VScode is too good), but in this case it makes a lot of sense (mostly as a self documentation). But I agree again - getting rid of `options` still seems like a solid win :)

And as a side note - I have this crazy idea to try and add Typescript support for Apostrophe. I'll do some research at some point and I'll let you know about the options we have. Just to be clear - it's about adding type definitions and NOT rewriting the core to .ts (I'm not that crazy).
