### ISSUE TITLE
marking boolean field with "required: true" does not let you save field with value of no/false

### ISSUE THREAD

**Issue by mtthwmnc** [apostrophecms/apostrophe#3277]
PLEASE NOTE: make sure the bug exists in the latest patch level of the project. For instance, if you are running a 2.x version of Apostrophe, you should use the latest in that major version to confirm the bug.

## To Reproduce

Step by step instructions to reproduce the behavior:

> 1. Create `boolean` schema field with `reuquired: true`

## Expected behavior
> No selection is initially made, user must select yes or no

## Describe the bug
> Selecting No/False results in required field error state

## Details

**Version of Node.js:**
v12.22.3

**Server Operating System:**
Mac OS 11.2.3 / Big Sur

**Comment by boutell** [comment]
(Closing, but cc'ing @stuartromanek here to make sure he agrees with my recollections and analysis. If not, we can reopen.)

This is intentional behavior in 3.x. It's unclear what else "required" could mean, since a checkbox has only two states. Otherwise we'd have to be able to save `null` (user made no selection) as a third value when not `required`, which is probably not what developers expect.

In 2.x we got stuck using a separate "mandatory: true" flag to do this, because we'd always intended `required: true` to make a boolean mandatory ("you can't proceed without agreeing to this"), but we didn't, and we caught it too late to avoid a bc break.

From the changelog for 2.x showing our thought process:

"`boolean` fields can now be made `mandatory`. If a boolean field is mandatory, the form will not validate unless the user selects "Yes." This is useful for simple "terms and conditions" forms. You must specify a message to be shown to the user if they do not select "Yes," like this:

```
{
  name: 'toc',
  label: 'Accept the Terms and Conditions',
  type: 'boolean',
  // Displayed if you try to save without picking Yes
  mandatory: 'You must accept the Terms and Conditions to continue.',
  // Always displayed
  help: 'I have read and accept the Terms and Conditions.'
}
```

Although the documentation formerly claimed that `required: true` would have this effect for boolean fields, it was pointed out that this functionality did not work, and as a result far too many sites already use `required: true` for booleans in a way that would break if we implemented the original documented behavior. Therefore we are changing the documentation to match this new implementation that maintains backwards compatibility."

All that being said, I can see situations where you want to force the user to make an explicit choice one way or the other and both choices are allowed. For that, you can use a `required` field of type `select` with "yes" and "no" values, and do conditional fields off that, and so on.
