### ISSUE TITLE
Custom Groups/Roles in Apostrophe 3?

### ISSUE THREAD

**Issue by mfreeman-xtivia** [apostrophecms/apostrophe#3282]
Is it possible to define/use custom groups in A3?

There is documentation that describes how to do this in A2, but i do not see any similar documentation for A2

**Comment by boutell** [comment]
Hi @mfreeman-xtivia, in A3 the standard permissions roles are "guest," "contributor," "editor" and "admin." Since all documents start out as drafts and contributors can work with drafts and submit them for review but cannot publish, this provides a simple workflow that replaces most common use cases for custom groups, up to a certain scale.

That being said, we understand there are larger scales where custom groups will still make sense, especially in the enterprise, which is why you can find Custom User Groups on our product board as an upcoming Apostrophe Assembly feature:

https://portal.productboard.com/apostrophecms/1-product-roadmap/tabs/2-planned

**Comment by mfreeman-xtivia** [comment]
So this will never be available in the non-Assembly, OSS version of Apostrophe 3??
