### ISSUE TITLE
Widget Selector Disappears in Column Configuration

### ISSUE THREAD

**Issue by egonzalezg9** [apostrophecms/apostrophe#3388]
In an area with a columns widget, the area widget selector disappears and the inner column area activates. Happens especially when column configuration is not 50/50, making the widget selector (+) button overlap directly with a column area. To reproduce: Create a columns widget that isn't 50/50, add content, and try to add another widget on top or below the column widget. Area widget selector will disappear. 

I think there needs to be additional padding or margin with the selector. Its area is fairly small so it's easy for it to disappear. 

Snapshots include view of area widget selector missing when trying to hover over the button. 
![Screenshot from 2021-09-03 09-04-03](https://user-images.githubusercontent.com/84875798/132055427-2721870f-a7f4-49da-b8d8-cc092fc0bd10.png)
![image](https://user-images.githubusercontent.com/84875798/132055596-52de2dab-a0ca-48e4-a8d2-d85ec08bb9c9.png)

**Comment by boutell** [comment]
cc @stuartromanek @agilbert

**Comment by stuartromanek** [comment]
@egonzalezg9 The outer area controls are still there but indeed are overlapped by the inner area's controls. 

Currently, Apostrophe doesn't impose opinions about how you might need to separate these nested widgets because it could interfere with the intended presentation of the website, but if the inner widgets don't somehow create their own space you can experience this.

To get you moving, you can always use any nested widget's breadcrumb UI as a wayfinder to your outer widgets. Simply click the name of the widget you'd like to focus. Once you do, the active controls on screen will be for corresponding widget.
<img width="620" alt="image" src="https://user-images.githubusercontent.com/1889830/132567769-cec7117e-1fec-4c7f-b873-cbcda5a83d9c.png">

This could still be irritating so I'm drafting a configuration option that would allow a developer to set a real margin on nested widgets. I will ping this thread when it's available.

**Comment by egonzalezg9** [comment]
Hey @stuartromanek, thanks for the suggestion. I did try it but the issue still happens. It does go to the outer widget, but then the button to add other widgets below or on top of it gets disabled. 

Appreciate the work on a configuration option. Miro had suggested adding the following CSS on discord (he implements it and I copied it). It works but of course it's probably not the ideal solution:
```
main [data-apos-area] {
   padding-top: 1rem;
   padding-bottom: 1rem;
}
```

**Comment by stuartromanek** [comment]
@egonzalezg9 ah ha, yeah that is another thing in your way that I didn't think of:

When you focus a widget, the Add (+) is unavailable. This was designed as a separation between editing a specific widget vs editing the larger area, but its not quite as helpful as intended, especially when relying on the breadcrumbs.

I'll follow up with another PR for removing the focus restriction.

**Comment by stuartromanek** [comment]
Two PRs in review that improve the ergonomics of working with nested areas:
- Keep Add Content controls accessible when widgets are focused #3410
- Nested widget spacing #3399
