### ISSUE TITLE
Server Side Event "beforeSave" fires twice?

### ISSUE THREAD

**Issue by mporembs** [apostrophecms/apostrophe#3563]
_FYI, I'm fairly new to this._

I've created a module for a type of piece. The piece needs to have a kml file attached to it that is fetched from a Garmin end point, with the desired start and end date/time passed as parameters in the request. Rather than fetch the kml myself and attach it as a file to the piece via the UI, I want to put the start and end dates and times in via the UI then fetch the kml from the end point on the backend.

I've made some progress myself. I've used the beforeSave server side event handler to successfully request and receive the kml. I've stopped there though, because for some reason any code I have in the beforeSave handler executes twice when one piece is saved or updated. I've removed all the log statements I had. But even with a single one, I get the console output twice every time. Index.js for the piece module is below.
 
```
module.exports = {
  extend: '@apostrophecms/piece-type',
  options: {
    label: 'Ride',
    // Additionally add a `pluralLabel` option if needed.
  },
  fields: {
    add: {
	    route: {
			label: 'GPX',
			type: 'attachment',
			fileGroup: 'gps'
		},
		trackDateStart: {
			label: 'Start Date',
			type: 'date',
			required: true
		},
		trackTimeStart: {
			label: 'Start Time',
			type: 'time',
			required: true
		},
		trackDateEnd: {
			label: 'End Date',
			type: 'date',
			required: false
		},
		trackTimeEnd: {
			label: 'End Time',
			type: 'time',
			required: false
		}
    },
    group: {
	    When: {
		    label: 'When',
		    fields: ['trackDateStart','trackTimeStart','trackDateEnd','trackTimeEnd']
	    },
	    What: {
		    label: 'What',
		    fields: ['route']
	    }
    }
  },
  handlers(self) {
    return {
      beforeSave: {
        async getGarminKML(req, piece) {
	        var fetch = require('node-fetch');
			inReachBaseURL = "https://share.garmin.com/Feed/Share/****redacted****?d1=";
			let beginUTC = new Date(piece.trackDateStart+"T"+piece.trackTimeStart).toISOString();
			let endUTC = new Date(piece.trackDateEnd+"T"+piece.trackTimeEnd).toISOString();
			kmlReqURL = inReachBaseURL.concat(beginUTC,"&d2=",endUTC);

			async function fetchAsync (url) {
			  let response = await fetch(url);
			  let data = await response.text();
			  return data;
			}
			
			try {
			kml = await fetchAsync(kmlReqURL);
				console.log("KML Received");
			}		
			catch (error){console.log("Error: ", error);}
		}
      },
    }
  }
};
```

**Comment by boutell** [comment]
Hi @mporembs,

Most likely you're seeing it fire twice because like most piece types, your piece type has separate draft and published versions of each document. It's possible to update just the draft by selecting "Save Draft," but since most people want to update the live version when they save their work, "Update" is the default option. So when "Update" is clicked, both the draft and the published version are updated, one followed by the other. That accounts for the two events.

If you need to make sure the work is not duplicated, you can create a new property of the document in `beforeSave` to record the fact that the data you need has already been fetched, or just check whether `aposMode` is `draft` or `published` and only do this work in the appropriate case.

**Comment by mporembs** [comment]
That had not occurred to me. Thanks for your help.

**Comment by boutell** [comment]
You're welcome, no trouble
