### ISSUE TITLE
Apostrophe fails to run in IE 11 support mode.

### ISSUE THREAD

**Issue by Miselrkba** [apostrophecms/apostrophe#3583]
I want to run Apostrophe in IE11 support mode. I followed the documentation in https://v3.docs.apostrophecms.org/guide/front-end-assets.html#supporting-internet-explorer-11 and added es5: true in asset/index.js

// modules/@apostrophecms/asset/index.js
module.exports = {
  options: {
    es5: true
  }
};
Apos fails to run with an error Select an appropriate 'target' to allow selecting one by default, or specify the 'output.chunkFormat' directly.

**Comment by abea** [comment]
Thanks for the report. I'll log this for follow up. I'm getting the same thing.

**Comment by mrBrownys** [comment]
any updates?

**Comment by boutell** [comment]
Unfortunately we haven't had a chance to look at this in a while. Since our customers, including large companies, have not expressed any interest in A3 IE11 builds and Microsoft is officially deleting IE11 from the remaining computers that run it in June and has already ended support in their own web application suite, it isn't very likely we'll get to it soon.

So this would be a good opportunity for a community contribution, or for sponsorship of the work. If you are interested in the latter please reach out to tom@apostrophecms.com and I can connect you with the appropriate person.

**Comment by boutell** [comment]
This was fixed some time ago and moved to a separate support module after Microsoft officially ended all support for IE11. Closing. See the changelog if you need more info about how to support IE11 (but you shouldn't, it's not receiving any security updates, better to tell your customer you can't accept the liability of encouraging them to use it)
