### ISSUE TITLE
use api to update relationship of the piece  did't work

### ISSUE THREAD

**Issue by sunnyzhifei** [apostrophecms/apostrophe#3780]
my version is  apostrophe@3.21.0, and i  want to update piece like goats-user, but its relationship field was set to [],
this is a picture .i dont know why and  how to fix it ,please help me . thank you.
and i have another question , i use self.apos.doc.db.updateOne to update piece  ,but the web not show latest info and api is ok ,I dont know how to fix it 

![image](https://user-images.githubusercontent.com/34208561/171853716-f87533bf-40c5-4a65-a7f7-2de2c39ca338.png)

**Comment by boutell** [comment]
Your first screenshot shows two levels of arrays (an array of tasks nested in an additional, extra array). You need just one flat array of tasks for the `_tasks` property.

As for why your direct MongoDB update did not alter the piece on the web, it is probably because you updated the draft but did not  publish the change to the live version of the document.

**Comment by sunnyzhifei** [comment]
> As for why your direct MongoDB update did not alter the piece on the web, it is probably because you updated the draft but did not publish the change to the live version of the document.
i updated id:en:published ,but its not useful
