### ISSUE TITLE
Hosting on Azure web app

### ISSUE THREAD

**Issue by joaom182** [apostrophecms/apostrophe#608]
Hi,

Azure Web Apps does not support ImageMagick, and not allows install this module. Has any way to run Apostrophe on Azure using Web Apps service without ImageMagick?

**Comment by boutell** [comment]
The uploadfs module can be configured to use a custom back end for image
processing. One could write one for the jimp module which is pure
JavaScript. Not sure offhand if jimp is capable enough but it is likely.

**Comment by boutell** [comment]
https://github.com/punkave/uploadfs/issues/13

**Comment by cwreamon** [comment]
Does anyone know if it is possible to deploy apostrophe on Azure? And if so is there any form of documentation?

**Comment by abea** [comment]
Not specific to Azure, but elements of [the Heroku guide](https://v2.docs.apostrophecms.org/devops/deployment/deploying-apostrophe-in-the-cloud-with-heroku.html#before-you-begin) might apply. Not completely, obviously.

**Comment by boutell** [comment]
Yes, major clients are deploying it successfully on Azure.

## Single server case

You didn't mention the scale of your project.

So first, let's talk about how to do this for a smaller project a lower cost:

Just get an Azure Ubuntu VM with a persistent disk. Then follow this HOWTO:

https://v2.docs.apostrophecms.org/devops/deployment/deployment.html

You're done!

## Running at scale

OK, that being said, let me talk about how to do it at scale. If this all sounds complicated to you then you probably just don't have this use case — you can run a quite popular regional website following the simpler path above.

1. See the uploadfs npm module documentation for how to use Azure blob storage as the persistent media upload storage. You can pass an `uploadfs` configuration option to the `@apostrophecms/uploadfs` (3.x) or `apostrophe-attachments` (2.x) module.

2. For MongoDB, I'd recommend using MongoDB Atlas — you can select any Azure region and Atlas will run there to ensure minimum latency between your application servers and MongoDB.

3. For execution of the app itself, you'd use Azure VMs and deploy to all of them. You can use an Azure load balancer because you took care of issues 1 and 2, so the application servers are stateless.
