### ISSUE TITLE
It would be nice if saving certain widgets could force a main content area refresh

### ISSUE THREAD

**Issue by LifeLockWWW** [apostrophecms/apostrophe#788]
As recommended by Punk Ave technical support we are implementing background images like this (see code at the end):

This method works but the image does not show up until you reload the page.  The image should show right away. 

<article class="row no-margin Sem-hero-dataBreach hero-cont"

                         {% set heroBackgroundAttachment = apos.images.first(data.page.heroBackground) %}

                         {% if heroBackgroundAttachment %}

                         style='background-image: url({{ apos.attachments.url(heroBackgroundAttachment,{size:"original"}) }})'

                         {% endif %}

                >

                <div class="hero-overlay"></div>

                {% if data.page._edit %}

                <div class="editHeroBackgroundContainer heroItems">

                    {{  apos.singleton(data.page, 'heroBackground', 'apostrophe-images',{label:"Hero Background Image",limit:1}) }}

                </div>

                {% endif %}

**Comment by boutell** [comment]
Apostrophe does not force a refresh of the main content area after every widget edit because normally, widgets do not have side effects outside themselves. This kind of technique introduces an exception to that rule, yes. We should think about adding a feature to optionally trigger `apos.change` when a widget with an appropriate option set is edited. Pull requests welcome.
