### ISSUE TITLE
Create official apostrophe confirm window

### ISSUE THREAD

**Issue by stuartromanek** [apostrophecms/apostrophe#916]
@stuart find the designs for this

**Comment by boutell** [comment]
`apos.notifications.trigger` is aliased as `apos.notify` to encourage adoption. So this should be aliased as `apos.confirm`.

I think the API should look like:

```
return apos.confirm('Are you sure you want to delete %s?', doc.title, function() { 
  // ... Do the thing ...
}, function() {
  // ... OPTIONAL function if they click cancel, usually omitted ...
});
```

This needs to be implemented with careful attention to the existing pattern for the `apostrophe-notifications` module. Like notify, confirm gets rendered on the server. Note the support for %s placeholders, which permits internationalization to happen on the server side when rendering the confirm modal. This won't be hard to achieve because we already did it for `apos.notify`, but it would be reasonable to implement just a string argument at first and ask me to port the %s stuff from notify.

This is not quite the usual function(err) { ... } callback interface because:

1. Errors are unexpected things. Clicking cancel is not an unexpected thing.

2. There really aren't any other possible interesting outcomes beyond "yes" and "no" (there are no errors, apart from a network error rendering the confirm modal, which is unlikely unless your whole Apostrophe experience is already pretty much failville).

3. It facilitates the easy refactoring of existing `confirm()` code, which looks like this:

```
if (confirm('Really?')) {
  // DO THE THING
}
```

There is almost never an "else" clause here.

That code just becomes:

```
// I LIKE THIS
return apos.confirm('Really?', function() {
  // DO THE THING
});
```

I think the convenience of this is a win over something like "clicking 'cancel' is an error":

```
// I DON'T LIKE THIS

return apos.confirm('Really?', function(err) {
  if (err) {
    return;
  }
  // DO THE THING
});
```

Should this code live in the `apostrophe-notifications` module? I am leaning toward yes. They will hopefully share some implementation details, and in the end both are aliased onto `apos` anyway.

**Comment by stuartromanek** [comment]
Attaching some designs. Not sure the green/red button pattern is always applicable
![apos-confirm-alt](https://user-images.githubusercontent.com/1889830/27746817-aec9d110-5d96-11e7-8540-6ff26639beae.png)
![apos-confirm](https://user-images.githubusercontent.com/1889830/27746816-aec7a2b4-5d96-11e7-8267-5e56d37f00f7.png)

**Comment by boutell** [comment]
My earlier notes about the ways people most often use the API are dead wrong. Some of our code has to take action in the "yes" case, some of it in the "no" case (to close a modal, for instance).

Given that, I think a more traditional callback API makes more sense:

```
return apos.confirm('Confirm Thing', { subtitle, okLabel, cancelLabel }, function(err) {
  if (err) {
    // cancel here
  } else {
    // do the thing here
  }
});
```

If the user clicks the cancel button, "err" will be truthy. I suggest it be the string `cancel` for easy testing in case anyone wants to be picky and double check whether it's a network error rendering the confirm modal or an actual user cancel action, but either way, treating it as a "no" is the only sensible thing to do.
